'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');global.window=global;for(const f of fs.readdirSync('assets/data').filter(f=>f.endsWith('-bank.js')))vm.runInThisContext(fs.readFileSync('assets/data/'+f,'utf8'));require('../games/sudoku/engine.js');require('../assets/js/scene-art.js');
const B=SistersBanks,counts={},directions=[[1,0],[-1,0],[0,1],[0,-1]];
function each(game,fn){counts[game]={};for(const[k,items]of Object.entries(B[game])){assert.equal(items.length,50);assert.equal(new Set(items.map(q=>q.id)).size,50);for(const q of items)fn(q,k);counts[game][k]=items.length;}}
each('sudoku',(q)=>{assert(SudokuEngine.isValidBoard(q.solution,q.size));assert(SudokuEngine.isValidBoard(q.puzzle,q.size,true));assert.equal(SudokuEngine.countSolutions(q.puzzle,q.size),1);assert.equal(q.puzzle.flat().filter(Boolean).length,q.clues);q.puzzle.forEach((r,y)=>r.forEach((v,x)=>assert(!v||v===q.solution[y][x])));});
each('memory',q=>{const pairs=new Map();q.layout.forEach(p=>pairs.set(p,(pairs.get(p)||0)+1));assert([...pairs.values()].every(n=>n===2));assert.equal(pairs.size,q.layout.length/2);});
// Independently normalize mirror/rotation and arbitrary pair labels.
for(const [n,items]of Object.entries(B.memory)){
 const [w,h]=({12:[4,3],16:[4,4],24:[6,4],36:[6,6]})[n],keys=[];
 for(const q of items){const forms=[];for(let flip=0;flip<2;flip++)for(let turn=0;turn<(w===h?4:1);turn++){const a=Array(+n);q.layout.forEach((v,i)=>{let x=i%w,y=Math.floor(i/w);if(flip)x=w-1-x;for(let k=0;k<turn;k++)[x,y]=[w-1-y,x];a[y*w+x]=v;});const labels=new Map();forms.push(a.map(v=>{if(!labels.has(v))labels.set(v,labels.size);return labels.get(v);}).join(','));}if(w!==h){for(const a of [q.layout.slice().reverse(),Array.from({length:+n},(_,i)=>q.layout[(h-1-Math.floor(i/w))*w+i%w])]){const labels=new Map();forms.push(a.map(v=>{if(!labels.has(v))labels.set(v,labels.size);return labels.get(v);}).join(','));}}keys.push(forms.sort()[0]);}assert.equal(new Set(keys).size,50,'memory mirrored pair topology '+n);
}
each('visual',(q,k)=>{assert.equal(q.n,6);assert.equal(new Set(q.targets).size,+k);assert(q.targets.every(n=>n>=0&&n<36));});
each('maze',q=>{assert.equal(q.grid.length,2*q.logicalSize+1);const seen=new Set([q.start.row+','+q.start.col]),Q=[[q.start.row,q.start.col]];for(let i=0;i<Q.length;i++)for(const[dy,dx]of directions){const[y,x]=Q[i],key=[y+dy,x+dx].join();if(q.grid[y+dy]?.[x+dx]===0&&!seen.has(key)){seen.add(key);Q.push([y+dy,x+dx]);}}assert.equal(seen.size,2*q.logicalSize*q.logicalSize-1);assert.equal(q.solution.length-1,q.pathLength);q.solution.forEach(([y,x],i)=>{assert.equal(q.grid[y][x],0);if(i)assert.equal(Math.abs(y-q.solution[i-1][0])+Math.abs(x-q.solution[i-1][1]),1);});assert.deepEqual(q.solution[0],[q.start.row,q.start.col]);assert.deepEqual(q.solution.at(-1),[q.goal.row,q.goal.col]);});
each('hanoi',q=>{const v=q.start.slice();for(const[from,to]of q.solution){const disc=v.indexOf(from),target=v.indexOf(to);assert(disc>=0&&from!==to&&(target<0||disc<target));v[disc]=to;}assert.deepEqual(v,q.goal);assert.equal(q.solution.length,q.minMoves);const Q=[q.start],seen=new Set([q.start.join()]);let depth=0,front=0;while(front<Q.length){const end=Q.length;for(;front<end;front++){const a=Q[front];if(a.join()===q.goal.join()){assert.equal(depth,q.minMoves);return;}for(let from=0;from<3;from++){const d=a.indexOf(from);if(d<0)continue;for(let to=0;to<3;to++){const t=a.indexOf(to);if(to===from||t>=0&&t<d)continue;const b=a.slice();b[d]=to;const key=b.join();if(!seen.has(key)){seen.add(key);Q.push(b);}}}}depth++;}assert.fail('Hanoi impossible');});
each('pattern',q=>{assert.equal(new Set(q.choices).size,q.choices.length);assert.equal(q.choices.filter(a=>a===q.answer).length,1);if(q.kind==='repeat'){assert.deepEqual(q.items,q.unit.concat(q.unit));assert.equal(q.answer,q.unit[0]);}if(q.kind==='add'){assert(q.items.every((v,i)=>+v===q.start+i*q.step));assert.equal(+q.answer,q.start+4*q.step);}if(q.kind==='groups'){assert(q.items.every((v,i)=>+v===q.start+Math.floor(i/q.repeat)*q.step));assert.equal(+q.answer,q.start+Math.floor(q.length/q.repeat)*q.step);}});
function slideNext(ps){const out=[];ps.forEach((p,i)=>{const vertical=p.h>p.w,others=new Set();ps.forEach((o,j)=>{if(i!==j)for(let y=0;y<o.h;y++)for(let x=0;x<o.w;x++)others.add([o.r+y,o.c+x].join());});for(const s of[-1,1])for(let n=1;n<6;n++){const r=p.r+(vertical?s*n:0),c=p.c+(vertical?0:s*n);if(r<0||c<0||r+p.h>6||c+p.w>6||Array.from({length:p.h*p.w},(_,k)=>[r+Math.floor(k/p.w),c+k%p.w].join()).some(k=>others.has(k)))break;const next=ps.map(o=>({...o}));next[i].r=r;next[i].c=c;out.push(next);}});return out;}
each('sliding',(q,k)=>{const occupied=new Set();q.pieces.forEach(p=>{assert(p.w===1||p.h===1);assert(p.r>=0&&p.c>=0&&p.r+p.h<=6&&p.c+p.w<=6);for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++){const key=[p.r+y,p.c+x].join();assert(!occupied.has(key));occupied.add(key);}});const start=q.pieces.map(p=>({...p}));let ps=start;for(const[i,dr,dc]of q.solution){const next=slideNext(ps).find(n=>n[i].r===ps[i].r+dr&&n[i].c===ps[i].c+dc&&n.every((p,j)=>j===i||p.r===ps[j].r&&p.c===ps[j].c));assert(next);ps=next;}assert(ps.find(p=>p.target).c+2===6);assert.equal(q.minimumMoves,+k);let frontier=[start],seen=new Set([JSON.stringify(start)]),minimum=null;for(let d=0;d<=4&&minimum===null;d++){const next=[];for(const p of frontier){if(p.find(t=>t.target).c+2===6){minimum=d;break;}for(const n of slideNext(p)){const key=JSON.stringify(n);if(!seen.has(key)){seen.add(key);next.push(n);}}}frontier=next;}assert.equal(minimum,q.minimumMoves);});
each('stroke',(q,k)=>{assert.equal(q.solution.length,q.edges.length+1);const seen=new Set();q.solution.slice(1).forEach((v,i)=>{const a=q.solution[i],e=q.edges.findIndex(([x,y])=>x===a&&y===v||x===v&&y===a);assert(e>=0&&!seen.has(e));seen.add(e);});const bounds={easy:[8,24],normal:[26,40],hard:[42,60]}[k];assert(q.edges.length>=bounds[0]&&q.edges.length<=bounds[1]);});
each('sokoban',(q,k)=>{let rows=q.rows.map(r=>r.split('')),boxes=rows.flat().filter(v=>v==='$'||v==='*').length,goals=rows.flat().filter(v=>'.*+'.includes(v)).length;assert.equal(boxes,+k);assert.equal(goals,boxes);assert(!rows.flat().includes('*'),'all boxes begin off targets');const floor=[];rows.forEach((r,y)=>r.forEach((v,x)=>{if(v!=='#')floor.push([x,y]);}));const seen=new Set([floor[0].join()]),queue=[floor[0]];for(let i=0;i<queue.length;i++)for(const[dx,dy]of directions){const[x,y]=queue[i],key=[x+dx,y+dy].join();if(rows[y+dy]?.[x+dx]!==undefined&&rows[y+dy][x+dx]!=='#'&&!seen.has(key)){seen.add(key);queue.push([x+dx,y+dy]);}}assert.equal(seen.size,floor.length);for(const[dx,dy]of q.solution){let x,y;rows.forEach((r,yy)=>r.forEach((v,xx)=>{if(v==='@'||v==='+'){x=xx;y=yy;}}));assert(x!==undefined);const nx=x+dx,ny=y+dy,t=rows[ny]?.[nx];assert(t&&t!=='#');if('$*'.includes(t)){const b=rows[ny+dy]?.[nx+dx];assert(b===' '||b==='.');rows[ny+dy][nx+dx]=b==='.'?'*':'$';}rows[ny][nx]='.*'.includes(t)?'+':'@';rows[y][x]=rows[y][x]==='+'?'.':' ';}assert(!rows.flat().includes('$'));assert.equal(q.solution.length,q.minimumMoves);});
each('scenes',q=>{assert.equal(new Set(q.objects.map(o=>o.cell)).size,q.objects.length);assert.equal(q.changes.length,3);assert.equal(new Set(q.changes.map(c=>c.kind)).size,3);const spots=SistersSceneArt.spots(q);for(let i=0;i<spots.length;i++)for(let j=i+1;j<spots.length;j++){const a=spots[i],b=spots[j];assert(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y));}for(const sp of spots)assert(sp.x>=0&&sp.y>=0&&sp.x+sp.w<=100&&sp.y+sp.h<=100);assert.notEqual(SistersSceneArt.svg(q.theme,q),SistersSceneArt.svg(q.theme,q,true));});
fs.mkdirSync('outputs/r3',{recursive:true});fs.writeFileSync('outputs/r3/bank-counts.json',JSON.stringify(counts,null,2));console.log('PASS bank solutions and declared difficulty',counts);
