'use strict';
function makeSolver(page,idle,payload){const click=async selector=>{await page.locator(selector).click();await idle();};
async function solve(game){const p=await payload();
 if(game==='maze'){const route=await page.evaluate(()=>{const s=MazeGame.getState(),q=[[s.playerPosition.row,s.playerPosition.col]],prev=new Map([[q[0].join(),null]]);for(let i=0;i<q.length;i++){const[y,x]=q[i];if(y===s.goal.row&&x===s.goal.col)break;for(const[dy,dx]of[[1,0],[-1,0],[0,1],[0,-1]]){const next=[y+dy,x+dx];if(s.maze[next[0]]?.[next[1]]===0&&!prev.has(next.join())){prev.set(next.join(),[y,x]);q.push(next);}}}const out=[];for(let a=[s.goal.row,s.goal.col];prev.get(a.join());){const b=prev.get(a.join());out.push(a[0]>b[0]?'ArrowDown':a[0]<b[0]?'ArrowUp':a[1]>b[1]?'ArrowRight':'ArrowLeft');a=b;}return out.reverse();});for(let i=0;i<route.length;i++){await page.keyboard.press(route[i]);if(i<route.length-1)await idle();}}
 if(game==='sudoku'){const holes=[];p.puzzle.forEach((r,y)=>r.forEach((v,x)=>{if(!v)holes.push([y,x,p.solution[y][x]])}));for(let i=0;i<holes.length;i++){const[y,x,n]=holes[i];await click(`[data-row="${y}"][data-col="${x}"]`);await page.locator('#answers button').nth(n-1).click();if(i<holes.length-1)await idle();}}
 if(game==='memory'){const pairs=new Map();p.deck.forEach((c,i)=>{const a=pairs.get(c.icon)||[];a.push(i);pairs.set(c.icon,a);});let done=0;for(const a of pairs.values()){await click('#grid button:nth-child('+(a[0]+1)+')');await page.locator('#grid button').nth(a[1]).click();if(++done<pairs.size)await idle();}}
 if(game==='visual'){await page.waitForFunction(()=>SistersRound.current().payload.phase==='play');for(let i=0;i<p.targets.length;i++){await page.locator('#grid button').nth(p.targets[i]).click();if(i<p.targets.length-1)await idle();}}
 if(game==='pattern'){await page.locator('#choices button').nth(p.answer).click();}
 if(game==='hanoi'){for(let i=0;i<p.question.solution.length;i++){const[from,to]=p.question.solution[i];await click('#pegs .peg:nth-child('+(from+1)+')');await page.locator('#pegs .peg').nth(to).click();if(i<p.question.solution.length-1)await idle();}}
 if(game==='sokoban'){for(let i=0;i<p.question.solution.length;i++){const[dx,dy]=p.question.solution[i];await page.keyboard.press(dx===1?'ArrowRight':dx===-1?'ArrowLeft':dy===1?'ArrowDown':'ArrowUp');if(i<p.question.solution.length-1)await idle();}}
 if(game==='stroke'){for(let i=0;i<p.question.solution.length;i++){await page.locator(`[data-n="${p.question.solution[i]}"]`).click();if(i<p.question.solution.length-1)await idle();}}
 if(game==='spot'){const hits=await page.locator('.hit').count();for(let i=0;i<hits;i++){await page.locator('.hit').nth(i).click();if(i<hits-1)await idle();}}
 if(game==='puzzle'){for(let i=0;i<p.placed.length;i++){await click(`[data-piece="${i}"]`);await page.locator('#board>.puzzle-slot').nth(i).click();if(i<p.placed.length-1)await idle();}}
 if(game==='sliding'){await page.locator('#board').scrollIntoViewIfNeeded();for(let i=0;i<p.question.solution.length;i++){const[index,dr,dc]=p.question.solution[i],block=await page.locator('#board .block').nth(index).boundingBox(),board=await page.locator('#board').boundingBox();await page.mouse.move(block.x+block.width/2,block.y+block.height/2);await page.mouse.down();await page.mouse.move(block.x+block.width/2+dc*board.width/6,block.y+block.height/2+dr*board.height/6,{steps:5});await page.mouse.up();if(i<p.question.solution.length-1)await idle();}}
 if(game==='tangram'){const ids=Object.keys(p.pieces);for(let i=0;i<ids.length;i++){const id=ids[i],t=p.question.parts[id],poly=page.locator(`[data-id="${id}"]`);await poly.focus();for(let k=0;k<t[2];k++){await page.keyboard.press('r');await idle();}if(t[3]){await page.keyboard.press('f');await idle();}const points=await page.evaluate(({id,t})=>{const current=SistersRound.current().payload.pieces[id],a=TangramRules.geometry(id,current),b=TangramRules.geometry(id,t),svg=document.getElementById('board'),matrix=svg.getScreenCTM(),center=ps=>new DOMPoint(ps.reduce((s,p)=>s+p[0],0)/ps.length,ps.reduce((s,p)=>s+p[1],0)/ps.length).matrixTransform(matrix);const x=center(a),y=center(b);return{x:x.x,y:x.y,tx:y.x,ty:y.y};},{id,t});await page.mouse.move(points.x,points.y);await page.mouse.down();await page.mouse.move(points.tx,points.ty,{steps:8});await page.mouse.up();if(i<ids.length-1)await idle();}}
}
return solve;}
module.exports={makeSolver};
