'use strict';
const assert=require('assert/strict'),C=require('../assets/js/family-core.js');let count=0;
const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
function setup(){const s=C.empty();s.credential={algorithm:'PBKDF2-SHA256',iterations:600000,salt:'0'.repeat(32),hash:'1'.repeat(64)};C.grant(s,'guest',10000,1000,'session');return s;}
function start(s,t=2000){const r={id:'round',game:'maze',player:'guest',status:'active',startedAt:t,sessionId:s.session.id,payload:{position:[1,1]}};C.round(s,r);s.active={id:r.id,game:r.game,player:r.player};return r;}
test('exact normal deadline prevents new round, keeps existing',()=>{const s=setup(),r=start(s);assert(C.canStart(s,'guest',10999));assert(!C.canStart(s,'guest',11000));C.advance(s,11000);assert.equal(s.session.phase,'grace');assert(C.canPlay(s,r,11000));});
test('no active round locks at expiry',()=>{const s=setup();C.advance(s,11000);assert.equal(s.session.phase,'locked');assert.equal(s.players.guest.debtMs,0);});
test('round at deadline is ineligible for grace',()=>{const s=setup();start(s,11000);C.advance(s,11000);assert.equal(s.session.phase,'locked');});
test('precise visible interval, duplicate and overlap deduplicated',()=>{const s=setup();start(s);C.observe(s,{sessionId:'session',roundId:'round',from:10800,to:11457});C.observe(s,{sessionId:'session',roundId:'round',from:10800,to:11457});C.observe(s,{sessionId:'session',roundId:'round',from:11400,to:11701});assert.equal(s.session.overtimeMs,701);});
test('background wall clock consumes grace and durably saves exact payload without observed debt',()=>{const s=setup();const r=start(s),payload=structuredClone(r.payload);C.advance(s,611000);assert.equal(s.session.phase,'locked');assert.equal(s.players.guest.debtMs,0);assert.equal(s.active,null);assert.equal(r.status,'saved');assert.equal(r.savedAt,611000);assert.deepEqual(r.payload,payload);});
test('observation clamps at exact hard deadline',()=>{const s=setup();start(s);C.observe(s,{sessionId:'session',roundId:'round',from:610990,to:999999});C.advance(s,999999);assert.equal(s.players.guest.debtMs,10);assert.equal(s.session.endedAt,611000);});
test('completion ends grace and settles exactly once',()=>{const s=setup(),r=start(s);C.advance(s,11000);C.observe(s,{sessionId:'session',roundId:'round',from:11000,to:12713});r.status='completed';C.endRound(s,r,'completed',12713);C.endRound(s,r,'completed',12713);C.settle(s,999999,'duplicate');assert.equal(s.players.guest.debtMs,1713);assert.equal(s.events.length,1);assert.equal(s.session.endedAt,12713);});
test('saved and abandoned rounds cannot continue during grace',()=>{for(const kind of['saved','abandoned']){const s=setup(),r=start(s);C.advance(s,11000);r.status=kind;C.endRound(s,r,kind,11100);assert(!C.canPlay(s,r,11100));assert.equal(s.active,null);assert.equal(s.session.phase,'locked');}});
test('fractional-second debt carries without rounding',()=>{const s=setup();s.players.guest.debtMs=61234;let v=C.grant(s,'guest',60000,2000,'s2');assert.equal(v.available,0);assert.equal(v.debtMs,1234);assert(!C.canStart(s,'guest',2000));v=C.grant(s,'guest',60000,3000,'s3');assert.equal(v.available,58766);assert.equal(s.session.deadline,61766);assert.equal(v.debtMs,0);});
test('next grant settles ongoing overtime before deduction',()=>{const s=setup();start(s);C.observe(s,{sessionId:'session',roundId:'round',from:11000,to:11999});const v=C.grant(s,'guest',15000,11999,'s2');assert.equal(v.available,14001);assert.equal(C.active(s).sessionId,'s2');assert(C.canPlay(s,C.active(s),12000));});
test('switch grant saves previous player and keeps separate debt',()=>{const s=setup();start(s);s.players.guest.debtMs=53;C.grant(s,'sister',10000,2500,'s2');assert.equal(s.active,null);assert.equal(s.rounds.guest.maze.status,'saved');assert.equal(s.players.guest.debtMs,53);assert.equal(s.players.sister.debtMs,0);});
test('stale session/round observations cannot add debt',()=>{const s=setup(),r=start(s);for(const o of[{sessionId:'other',roundId:r.id},{sessionId:'session',roundId:'other'}])assert.equal(C.observe(s,{...o,from:11000,to:12000}),0);r.status='saved';assert.equal(C.observe(s,{sessionId:'session',roundId:r.id,from:11000,to:12000}),0);});
test('serialization retains precise state and old payload',()=>{const s=setup();start(s);C.observe(s,{sessionId:'session',roundId:'round',from:11000,to:11001});const copy=C.validate(JSON.parse(JSON.stringify(s)));assert.deepEqual(copy,s);});
test('invalid storage fails without inventing a new state',()=>{const s=setup();s.players.guest.debtMs=-1;assert.throws(()=>C.validate(s));assert.throws(()=>C.grant(setup(),'guest',0,1000,'s'));});
console.log(JSON.stringify({passed:count}));
