'use strict';
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const oldURL='http://127.0.0.1:8003',newURL=process.env.TEST_URL||'http://127.0.0.1:8005',games=['maze','sudoku','memory','sokoban','pattern','visual','spot','stroke','hanoi','puzzle','sliding','tangram'],pw='Migration-synthetic+long!2026';
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),rows=[];fs.mkdirSync('outputs/r3/migration',{recursive:true});
for(const game of games){const old=await b.newContext(),fresh=await b.newContext();for(const c of[old,fresh])await c.addInitScript(games=>{if(location.origin==='null')return;localStorage.setItem('sistersPuzzleCurrentPlayerV1','guest');localStorage.setItem('sistersMuted','1');for(const g of games)localStorage.setItem('sistersCoachSeenV1:'+g,'1');},games);const p=await old.newPage(),q=await fresh.newPage(),row={game,pass:false};q.setDefaultTimeout(7000);try{
await p.goto(oldURL+'/games/'+game+'/');if(game==='maze')await p.click('#start-game');if(game==='sudoku')await p.click('#start');await p.waitForFunction(()=>SistersRound.canInteract());
if(['puzzle','sliding','tangram'].includes(game))await p.click('#hint');if(game==='memory')await p.locator('#grid button').first().click();if(game==='stroke')await p.locator('[data-n="0"]').click();if(game==='pattern')await p.locator('#choices button').first().click();if(game==='spot')await p.locator('.hit').first().click();if(game==='sudoku'){await p.locator('.editable').first().click();await p.locator('#answers button').first().click();}if(game==='hanoi'){await p.locator('#pegs .peg').first().click();await p.locator('#pegs .peg').nth(1).click();}await p.waitForTimeout(60);const legacy=await p.evaluate(()=>localStorage.getItem(SistersRound.KEY)),before=JSON.parse(legacy).round;
await q.goto(newURL+'/');await q.evaluate(({legacy})=>{localStorage.removeItem('sistersFamilyV3');localStorage.setItem('sistersRoundLifecycleV1',legacy);localStorage.setItem('sistersGameResultsV1',JSON.stringify(Array.from({length:401},(_,i)=>({roundId:'synthetic-old-'+i,game:'historical',moves:i}))));localStorage.setItem('mazeAdventureRecordsV1',JSON.stringify({version:1,players:{guest:{hard:{completions:9,bestMs:88000}},sister:{easy:{completions:5,bestMs:60001}}},fictionalMarker:'keep'}));},{legacy});await q.goto(newURL+'/games/'+game+'/');await q.waitForFunction(()=>SistersRound.current()?.payload);assert.equal((await q.evaluate(()=>SistersRound.current())).id,before.id);assert.equal(await q.evaluate(()=>SistersRound.canInteract()),false);
await q.click('#family-open');await q.fill('#parent-password',pw);await q.fill('#parent-confirm',pw);await q.locator('#parent-auth button[type=submit]').click();await q.waitForFunction(()=>!document.getElementById('parent-authorized').hidden);await q.locator('#parent-duration button[type=submit]').click();await q.waitForFunction(()=>SistersRound.canInteract());const after=await q.evaluate(()=>SistersRound.current());assert.equal(after.id,before.id);for(const key of['pieces','placed','entries','solution','rows','targets','found','used','pegs','deck','open','round','playerPosition','visited'])if(before.payload[key]!==undefined)assert.deepEqual(after.payload[key],before.payload[key],game+' '+key);assert.equal((await q.evaluate(()=>JSON.parse(localStorage.getItem('sistersGameResultsV1')))).length,401);assert.equal((await q.evaluate(()=>JSON.parse(localStorage.getItem('mazeAdventureRecordsV1')))).fictionalMarker,'keep');await q.reload();await q.waitForFunction(()=>SistersRound.canInteract());assert.equal((await q.evaluate(()=>SistersRound.current())).id,before.id);row.pass=true;console.log('PASS old R2 exact migration',game);
}catch(e){row.error=e.message;await q.screenshot({path:'outputs/r3/migration/'+game+'-failure.png',fullPage:true});console.error('FAIL migration',game,e.message);}finally{rows.push(row);await old.close();await fresh.close();}}
await b.close();fs.writeFileSync('outputs/r3/migration-browser.json',JSON.stringify(rows,null,2));if(rows.some(r=>!r.pass))process.exitCode=1;})();
