'use strict';
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const games=['maze','sudoku','memory','puzzle','hanoi','sliding','sokoban','stroke','tangram','visual','pattern','spot'].filter(g=>!process.env.TEST_GAMES||process.env.TEST_GAMES.split(',').includes(g)),base=process.env.TEST_URL||'http://127.0.0.1:8005';
const views=[{width:1366,height:768},{width:1920,height:1080},{width:1024,height:700},{width:911,height:512},{width:683,height:384},{width:390,height:844},{width:844,height:390}];
(async()=>{fs.mkdirSync('outputs/r3/modes',{recursive:true});const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const ctx=await b.newContext({viewport:views[0]});await ctx.addInitScript(games=>{if(location.origin==='null')return;localStorage.setItem('sistersPuzzleCurrentPlayerV1','guest');localStorage.setItem('sistersMuted','1');for(const g of games)localStorage.setItem('sistersCoachSeenV1:'+g,'1');},games);const p=await ctx.newPage(),rows=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(5000);await p.goto(base+'/');await p.evaluate(async()=>{await SistersFamily.ready;await SistersFamily.transact(s=>{s.credential={algorithm:'PBKDF2-SHA256',iterations:600000,salt:'12'.repeat(16),hash:'34'.repeat(32)};SistersFamilyCore.grant(s,'guest',7200000,Date.now(),'synthetic-ui-session');});});
async function active(){await p.waitForFunction(()=>SistersRound.canInteract());}
try{for(const game of games){let modes=[];if(game==='maze')for(const memory of[false,true])for(const difficulty of['easy','normal','hard','super'])modes.push({memory,difficulty});else if(game==='sudoku')for(const size of[4,6])for(const mode of['number','picture'])for(const difficulty of['practice','easy','challenge'])modes.push({size,mode,difficulty});else if(game==='memory')for(const size of[0,1,2,3])for(const theme of['animal','fruit','car','food','shape'])modes.push({size,theme});else if(game==='puzzle')for(const art of['garden','room','sea'])for(const pieces of[12,24,36])modes.push({art,pieces});else if(game==='hanoi')modes=[3,4,5,6,7].map(n=>({value:n}));else{const values={sliding:['1','2','3','4'],sokoban:['1','2','3'],stroke:['easy','normal','hard'],tangram:['outline','partial','silhouette'],visual:[0,1,2,3,4],pattern:['repeat','add','groups'],spot:[0,1,2,3,4,5,6,7,8,9]}[game];modes=values.map(value=>({value}));}
for(let i=0;i<modes.length;i++){const mode=modes[i],row={game,mode,views:[],pass:false};await p.setViewportSize(views[0]);await p.goto(base+'/games/'+game+'/'+(mode.memory?'#memory':''));
if(game==='maze'){if(await p.evaluate(()=>['active','saved'].includes(SistersFamily.read().rounds.guest?.maze?.status))){await active();await p.evaluate(()=>SistersRound.abandon());}await p.goto(base+'/games/maze/'+(mode.memory?'#memory':''));await p.reload();if(await p.locator('#start-game').isVisible()){await p.locator(`[data-difficulty="${mode.difficulty}"]`).click();await p.click('#start-game');}else await p.selectOption('.game-actions select',mode.difficulty);}
else if(game==='sudoku'){if(await p.locator('#back-setup').isVisible())await p.click('#back-setup');for(const k of['size','mode','difficulty'])await p.locator(`[data-setting="${k}"][data-value="${mode[k]}"]`).click();await p.click('#start');}
else{await p.waitForFunction(()=>SistersRound.current()?.payload);if(await p.evaluate(()=>SistersRound.current()?.status==='active'))await active();if(game==='memory'){await p.selectOption('#size-row select',String(mode.size));await active();await p.selectOption('#theme-row select',mode.theme);}else if(game==='puzzle'){await p.selectOption('#size-row select',String(mode.pieces));await active();await p.selectOption('#art-row select',mode.art);}else{const id={hanoi:'disc-row',sliding:'tier-row',sokoban:'level-row',stroke:'level-row',tangram:'level-row',visual:'level-row',pattern:'tier-row',spot:'diff-row'}[game];await p.selectOption('#'+id+' select',String(mode.value));}}
await active();const r=await p.evaluate(()=>SistersRound.current());row.challenge=r.payload.question?.id||r.payload.challengeId||null;
for(const view of views){await p.setViewportSize(view);await p.waitForTimeout(30);const m=await p.evaluate(()=>{const ids=['maze','board','grid','pegs','seq','scene'];const board=ids.map(id=>document.getElementById(id)).find(el=>el&&el.getBoundingClientRect().width>0);const r=board?.getBoundingClientRect();return{width:innerWidth,scrollWidth:document.documentElement.scrollWidth,board:r?{width:r.width,height:r.height,x:r.x,y:r.y}:null};});assert(m.scrollWidth<=view.width+1,game+' overflow '+JSON.stringify(m));assert(m.board&&m.board.width>=150&&m.board.x>=-1&&m.board.x+m.board.width<=view.width+1);row.views.push({...view,...m});}
await p.setViewportSize(views[0]);await p.screenshot({path:'outputs/r3/modes/'+game+'-'+String(i).padStart(2,'0')+'.png',fullPage:true});if(process.env.SOLVE_EVERY_MODE==='1'){const solve=require('./browser-helpers.cjs').makeSolver(p,active,()=>p.evaluate(()=>SistersRound.current().payload));await solve(game);await p.waitForFunction(()=>SistersRound.current()?.status==='completed');row.completed=true;await p.screenshot({path:'outputs/r3/modes/'+game+'-'+String(i).padStart(2,'0')+'-completed.png',fullPage:true});}row.pass=true;rows.push(row);console.log('PASS',game,i+1,'/',modes.length);
}}
assert.deepEqual(errors,[]);
}catch(e){console.error(e);await p.screenshot({path:'outputs/r3/modes/failure.png',fullPage:true});process.exitCode=1;}finally{fs.writeFileSync('outputs/r3/'+(process.env.TEST_GAMES?'modes-browser-affected':'modes-browser')+'.json',JSON.stringify({rows,errors},null,2));await b.close();}})();
