'use strict';
const {chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs');
const url=process.env.TEST_URL||'http://127.0.0.1:8005',password='R3-synthetic-only!long-2026',out='outputs/r3';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1366,height:768}});await context.addInitScript(()=>{const real=Date.now;window.__shift=0;Date.now=()=>real()+window.__shift;});const page=await context.newPage(),errors=[],passed=[];page.on('pageerror',e=>errors.push(e.message));
const check=async(name,fn)=>{await fn();passed.push(name);console.log('PASS',name)};
const state=()=>page.evaluate(()=>SistersFamily.read());const idle=()=>page.waitForFunction(()=>SistersRound.canInteract(),null,{timeout:10000});
async function coach(){for(let i=0;i<6&&await page.locator('.coach button').count();i++)await page.locator('.coach button').last().click();}
async function auth(first=false){await page.click('#family-open');await page.fill('#parent-password',password);if(first)await page.fill('#parent-confirm',password);await page.locator('#parent-auth button[type=submit]').click();await page.waitForFunction(()=>!document.getElementById('parent-authorized').hidden);}
async function grant(minutes='20'){await page.selectOption('#parent-minutes',minutes);await page.locator('#parent-duration button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('.family-dialog').open);}
try{
await page.goto(url+'/');await page.evaluate(()=>SistersFamily.ready);await page.click('[data-player="guest"]');
await check('first setting uses long salted KDF, hides input',async()=>{await auth(true);await page.screenshot({path:out+'/parent-settings.png',fullPage:true});const s=await state();assert(s.credential.salt.length===32&&s.credential.hash.length===64);assert(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes(password));assert.equal(await page.locator('#parent-password').getAttribute('type'),'password');await grant();});
await page.goto(url+'/games/puzzle/');await coach();await idle();
await check('return abandons once and releases immediately',async()=>{await page.click('#hint');await idle();const r=await page.evaluate(()=>SistersRound.current());await page.click('#back-home');await page.waitForURL('**/index.html#games/logic');const s=await state();assert.equal(s.active,null);assert.equal(s.rounds.guest.puzzle.status,'abandoned');assert.equal(s.events.filter(e=>e.type==='GameAbandoned'&&e.roundId===r.id).length,1);});
await page.goto(url+'/games/memory/');await coach();await idle();
let saved;
await check('save and cross-page resume retain exact progress and ID',async()=>{await page.locator('#grid button').first().click();await idle();saved=await page.evaluate(()=>SistersRound.current());await page.click('#round-save');await page.waitForURL('**/index.html#games/logic');assert.equal((await state()).rounds.guest.memory.status,'saved');await page.click('#round-resume');await page.waitForURL('**/games/memory/');await idle();const r=await page.evaluate(()=>SistersRound.current());assert.equal(r.id,saved.id);assert.deepEqual(r.payload.open,saved.payload.open);});
await check('reload keeps current round and authorization deadline',async()=>{const a=(await state()).session.deadline;await page.reload();await idle();assert.equal((await state()).session.deadline,a);assert.equal((await page.evaluate(()=>SistersRound.current())).id,saved.id);});
await check('wrong password and parent cancel cannot renew',async()=>{const id=(await state()).session.id;await page.click('#family-open');await page.fill('#parent-password','incorrect-synthetic!');await page.locator('#parent-auth button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('parent-message').textContent.includes('不正確'));assert.equal((await state()).session.id,id);await page.locator('#parent-auth [data-cancel]').click();assert.equal((await state()).session.id,id);await page.waitForFunction(()=>document.getElementById('parent-password').value==='');});
await check('expiry allows current round, blocks next game/restart',async()=>{const s=await state();await page.evaluate(deadline=>{window.__shift=deadline-Date.now()+500},s.session.deadline);await page.waitForFunction(()=>SistersFamily.read().session.phase==='grace');const r=await page.evaluate(()=>SistersRound.current());await page.click('#restart');await page.waitForTimeout(300);assert.equal((await page.evaluate(()=>SistersRound.current())).id,r.id);assert(await page.evaluate(()=>SistersRound.canInteract()));});
await page.screenshot({path:out+'/parent-grace-memory.png',fullPage:true});
await check('hard cutoff saves before locking, debt counted once',async()=>{const s=await state();await page.waitForTimeout(800);await page.evaluate(cutoff=>{window.__shift+=cutoff-Date.now()},s.session.graceUntil);await page.waitForFunction(()=>SistersFamily.read().session.phase==='locked'&&SistersFamily.read().rounds.guest.memory.status==='saved');const first=await state();await page.waitForTimeout(600);const second=await state();assert.equal(second.players.guest.debtMs,first.players.guest.debtMs);assert(second.players.guest.debtMs>0);assert.equal(second.active,null);assert.equal(second.rounds.guest.memory.id,saved.id);});
await check('authenticated renewal deducts precise debt and resumes saved round',async()=>{const debt=(await state()).players.guest.debtMs;await auth();await grant('10');await idle();const s=await state();assert.equal(s.session.deadline-s.session.startedAt,600000-debt);assert.equal(s.players.guest.debtMs,0);assert.equal((await page.evaluate(()=>SistersRound.current())).id,saved.id);});
await page.screenshot({path:out+'/parent-renewed-memory.png',fullPage:true});
await check('multi-tab rejects concurrent round owner without overwriting',async()=>{const other=await context.newPage();await other.goto(url+'/games/puzzle/');const b=other.locator('.coach button');if(await b.count())await b.last().click();await other.waitForTimeout(700);assert.equal((await state()).active.id,saved.id);assert.equal(await other.evaluate(()=>SistersRound.canInteract()),false);await other.close();});
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:passed.length,errors}));
}catch(e){await page.screenshot({path:out+'/parent-failure.png',fullPage:true});console.error(e);process.exitCode=1;}finally{fs.writeFileSync(out+'/parent-browser.json',JSON.stringify({passed,errors},null,2));await browser.close();}})();
