'use strict';
const{chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const games=['maze','sudoku','memory','puzzle','hanoi','sliding','sokoban','stroke','tangram','visual','pattern','spot'],base=process.env.TEST_URL||'http://127.0.0.1:8005';
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),p=await c.newPage(),rows=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(games=>{if(location.origin==='null')return;localStorage.setItem('sistersPuzzleCurrentPlayerV1','guest');for(const g of games)localStorage.setItem('sistersCoachSeenV1:'+g,'1');},games);await p.goto(base+'/');await p.evaluate(async()=>{await SistersFamily.ready;await SistersFamily.transact(s=>{s.credential={algorithm:'PBKDF2-SHA256',iterations:600000,salt:'90'.repeat(16),hash:'ab'.repeat(32)};SistersFamilyCore.grant(s,'guest',7200000,Date.now(),'synthetic-touch-session');});});const cdp=await c.newCDPSession(p),idle=()=>p.waitForFunction(()=>SistersRound.canInteract());
const locator=loc=>new Proxy(loc,{get(t,k){if(k==='click')return()=>t.tap();const v=t[k];if(typeof v==='function')return(...a)=>{const r=v.apply(t,a);return r&&typeof r.locator==='function'?locator(r):r;};return v;}});let pointer={x:0,y:0},down=false;
const touch=()=>cdp.send('Input.dispatchTouchEvent',{type:down?'touchMove':'touchEnd',touchPoints:down?[{...pointer,id:1}]:[]});
const inputPage={locator:s=>locator(p.locator(s)),waitForFunction:(...a)=>p.waitForFunction(...a),evaluate:(...a)=>p.evaluate(...a),keyboard:{press:async key=>{const dir={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[key];if(await p.locator('[data-move]').count())return p.locator('[data-move="'+dir+'"]').tap();if(await p.locator('[data-d]').count())return p.locator('[data-d="'+{ArrowUp:'0,-1',ArrowDown:'0,1',ArrowLeft:'-1,0',ArrowRight:'1,0'}[key]+'"]').tap();return p.locator(key==='r'?'#rotate':'#flip').tap();}},mouse:{move:async(x,y,o)=>{const from={...pointer};for(let i=1;i<=(o?.steps||1);i++){pointer={x:from.x+(x-from.x)*i/(o?.steps||1),y:from.y+(y-from.y)*i/(o?.steps||1)};if(down){await touch();await p.waitForTimeout(20);}}},down:async()=>{down=true;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...pointer,id:1}]});},up:async()=>{await p.waitForTimeout(50);down=false;await touch();await p.waitForTimeout(50);}}};
const solve=require('./browser-helpers.cjs').makeSolver(inputPage,idle,()=>p.evaluate(()=>SistersRound.current().payload));fs.mkdirSync('outputs/r3/touch',{recursive:true});
try{for(const game of games.filter(g=>!process.env.ONLY_GAME||g===process.env.ONLY_GAME)){await p.goto(base+'/games/'+game+'/');if(game==='maze')await p.locator('#start-game').tap();if(game==='sudoku')await p.locator('#start').tap();await idle();assert(await p.evaluate(()=>matchMedia('(pointer:coarse)').matches));await solve(game);fs.writeFileSync('outputs/r3/touch/'+game+'-state.json',JSON.stringify(await p.evaluate(()=>({round:SistersRound.current(),matched:window.TangramRules?.assignment()})),null,2));await p.waitForFunction(()=>SistersRound.current()?.status==='completed');await p.screenshot({path:'outputs/r3/touch/'+game+'.png',fullPage:true});rows.push({game,pass:true,input:'touch tap / CDP touch drag, coarse pointer 390x844'});console.log('PASS touch completion',game);}assert.deepEqual(errors,[]);}catch(e){rows.push({pass:false,error:e.message});await p.screenshot({path:'outputs/r3/touch/failure.png',fullPage:true});console.error(e);process.exitCode=1;}finally{fs.writeFileSync('outputs/r3/touch-browser.json',JSON.stringify({rows,errors},null,2));await b.close();}})();
