(()=>{
"use strict";
const ui=window.SistersShared,content=window.SISTERS_CONTENT,id=x=>document.getElementById(x);
const arts=[['cat','貓咪','🐱','#f7c5ce'],['dog','小狗','🐶','#d9b082'],['fruit','水果','🍓','#ffd6a5'],['car','車子','🚗','#bde0fe'],['dino','恐龍','🦕','#cdeac0'],['fish','小魚','🐟','#bfe8ef']];
const svg=([,name,emoji,color])=>`url("data:image/svg+xml,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 400'><rect width='400' height='400' fill='${color}'/><circle cx='70' cy='70' r='28' fill='#fff4b5'/><circle cx='330' cy='330' r='35' fill='#ffffff88'/><text x='200' y='245' text-anchor='middle' font-size='180'>${emoji}</text><text x='200' y='345' text-anchor='middle' font-family='sans-serif' font-weight='bold' font-size='34' fill='#543c4e'>${name}</text></svg>`)}")`;
const state={player:ui.loadPlayer(),art:arts[0],size:'2x2',tiles:[],selected:null,moves:0};
function back(){location.href='../../index.html#games/logic';}function dims(){return state.size.split('x').map(Number);}function complete(){return state.tiles.every((tile,index)=>tile===index);}
function shuffled(n){let a=Array.from({length:n},(_,i)=>i);do{for(let i=n-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}}while(a.every((v,i)=>v===i));return a;}
function renderArt(){const list=id('art-list');list.replaceChildren();arts.forEach(art=>{const b=document.createElement('button');b.className='art-button'+(art===state.art?' selected':'');b.type='button';b.style.background=art[3];b.textContent=`${art[2]} ${art[1]}`;b.onclick=()=>{state.art=art;renderArt();};list.append(b);});}
function render(){const[cols,rows]=dims(),art=svg(state.art),board=id('board');board.style.setProperty('--cols',cols);board.style.setProperty('--rows',rows);board.style.setProperty('--art',art);id('reference').style.setProperty('--art',art);board.replaceChildren();state.tiles.forEach((tile,index)=>{const b=document.createElement('button'),x=tile%cols,y=Math.floor(tile/cols);b.type='button';b.className='tile'+(state.selected===index?' selected':'');b.style.setProperty('--x',x);b.style.setProperty('--y',y);b.setAttribute('aria-label',`第 ${index+1} 塊`);b.onclick=()=>choose(index);board.append(b);});id('moves').textContent=`交換 ${state.moves} 次`;}
function choose(index){if(state.selected===index){state.selected=null;render();return;}if(state.selected===null){state.selected=index;id('message').textContent='再點一塊來交換';render();return;}[state.tiles[state.selected],state.tiles[index]]=[state.tiles[index],state.tiles[state.selected]];state.selected=null;state.moves++;render();if(complete()){id('complete-text').textContent=`你交換了 ${state.moves} 次！`;id('complete').hidden=false;}}
function start(){const[cols,rows]=dims();state.tiles=shuffled(cols*rows);state.moves=0;state.selected=null;id('setup').hidden=true;id('game').hidden=false;id('complete').hidden=true;id('message').textContent='點兩塊拼圖來交換';render();}
if(!content.players[state.player]){back();return;}id('player').replaceChildren(ui.makeReading(content.site.currentPlayer,{compact:true}),document.createTextNode('：'),ui.makeReading(content.players[state.player].name,{compact:true}));renderArt();document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{state.size=b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('selected',x===b));});id('start').onclick=start;id('back').onclick=back;id('back-setup').onclick=()=>{id('game').hidden=true;id('setup').hidden=false;};id('shuffle').onclick=start;id('again').onclick=start;id('home').onclick=back;window.PuzzleGame=Object.freeze({start,getState:()=>({...state,tiles:[...state.tiles]})});
})();
