(() => {
 "use strict";
 const ui=window.SistersShared,content=window.SISTERS_CONTENT,engine=window.SudokuEngine;
 const packs={animals4:["🐱","🐶","🐰","🐻"],animals6:["🐱","🐶","🐰","🐻","🐼","🦊"]};
 const state={playerId:ui.loadPlayer(),size:4,mode:"number",difficulty:"practice",puzzle:null,solution:null,entries:null,selected:null,completed:false,lastSignature:""};
 const id=name=>document.getElementById(name),copy=board=>board.map(row=>[...row]);
 function goList(){location.href="../../index.html#games/logic";}
 function label(value){return state.mode==="picture"?packs[`animals${state.size}`][value-1]:String(value);}
 function configurePlayer(){if(!content.players[state.playerId]){goList();return false;}id("player-badge").replaceChildren(ui.makeReading(content.site.currentPlayer,{compact:true}),document.createTextNode("："),ui.makeReading(content.players[state.playerId].name,{compact:true}));return true;}
 function selectOption(button){const setting=button.dataset.setting,value=button.dataset.value;state[setting]=setting==="size"?Number(value):value;document.querySelectorAll(`[data-setting="${setting}"]`).forEach(item=>{const selected=item===button;item.classList.toggle("selected",selected);item.setAttribute("aria-pressed",String(selected));});}
 function signature(puzzle){return puzzle.flat().join("");}
 function newPuzzle(){let made;for(let i=0;i<8;i+=1){made=engine.generatePuzzle(state.size,state.difficulty);if(signature(made.puzzle)!==state.lastSignature)break;}state.puzzle=copy(made.puzzle);state.solution=copy(made.solution);state.entries=copy(made.puzzle);state.lastSignature=signature(made.puzzle);state.selected=null;state.completed=false;id("complete").hidden=true;renderAll();}
 function showGame(){id("setup").hidden=true;id("game").hidden=false;newPuzzle();}
 function showSetup(){id("game").hidden=true;id("setup").hidden=false;}
 function cellClass(row,col,value){const classes=["sudoku-cell"];if(state.puzzle[row][col])classes.push("given");else classes.push("editable");if(state.selected&&state.selected.row===row&&state.selected.col===col)classes.push("selected");else if(state.selected&&(state.selected.row===row||state.selected.col===col||Math.floor(state.selected.row/(state.size===4?2:2))===Math.floor(row/2)&&Math.floor(state.selected.col/(state.size===4?2:3))===Math.floor(col/(state.size===4?2:3))))classes.push("related");if(value)classes.push("filled");return classes.join(" ");}
 function renderBoard(){const board=id("board"),boxCols=state.size===4?2:3;board.style.setProperty("--size",state.size);board.style.setProperty("--box-cols",boxCols);board.replaceChildren();state.entries.forEach((line,row)=>line.forEach((value,col)=>{const button=document.createElement("button");button.type="button";button.className=cellClass(row,col,value);button.dataset.row=row;button.dataset.col=col;button.textContent=value?label(value):"";button.disabled=Boolean(state.puzzle[row][col])||state.completed;button.setAttribute("aria-label",value?`${row+1}列${col+1}行 ${label(value)}`:`${row+1}列${col+1}行 空格`);if((col+1)%boxCols===0&&col<state.size-1)button.classList.add("box-right");if((row+1)%2===0&&row<state.size-1)button.classList.add("box-bottom");button.addEventListener("click",()=>selectCell(row,col));board.append(button);}));}
 function renderAnswers(){const pad=id("answers");pad.style.setProperty("--size",state.size);pad.replaceChildren();for(let value=1;value<=state.size;value+=1){const button=document.createElement("button");button.type="button";button.className="answer-button";button.textContent=label(value);button.disabled=state.completed;button.addEventListener("click",()=>enterValue(value));pad.append(button);}}
 function renderAll(){renderBoard();renderAnswers();id("game-meta").textContent=`${state.size}×${state.size}・${state.mode==="number"?"數字":"動物"}・${{practice:"練習 ⭐",easy:"簡單 ⭐⭐",challenge:"挑戰 ⭐⭐⭐"}[state.difficulty]}`;id("message").textContent="點一個空格，再選答案";}
 function selectCell(row,col){if(state.puzzle[row][col]||state.completed)return;state.selected={row,col};renderBoard();id("message").textContent="選一個答案吧！";}
 function flashCell(kind){if(!state.selected)return;const cell=id("board").querySelector(`[data-row="${state.selected.row}"][data-col="${state.selected.col}"]`);cell?.classList.add(kind);}
 function enterValue(value){if(!state.selected||state.completed){id("message").textContent="先點一個空格喔～";return;}const{row,col}=state.selected;if(value!==state.solution[row][col]){id("message").textContent="再想想看～";flashCell("oops");return;}state.entries[row][col]=value;renderBoard();flashCell("correct");id("message").textContent="答對了，繼續加油！";if(isComplete())finish();}
 function isComplete(){return state.entries.every((row,r)=>row.every((value,c)=>value===state.solution[r][c]));}
 function finish(){if(state.completed)return;state.completed=true;renderBoard();renderAnswers();id("complete").hidden=false;}
 function restart(){state.entries=copy(state.puzzle);state.selected=null;state.completed=false;id("complete").hidden=true;renderAll();}
 function hint(){if(state.completed)return;const blanks=[];state.entries.forEach((row,r)=>row.forEach((value,c)=>{if(!value)blanks.push({row:r,col:c});}));if(!blanks.length)return;const pick=blanks[Math.floor(Math.random()*blanks.length)];state.selected=pick;state.entries[pick.row][pick.col]=state.solution[pick.row][pick.col];renderBoard();flashCell("correct");id("message").textContent="小貓幫你填一格！";if(isComplete())finish();}
 document.querySelectorAll("[data-setting]").forEach(button=>button.addEventListener("click",()=>selectOption(button)));id("start").addEventListener("click",showGame);id("back-list").addEventListener("click",goList);id("back-setup").addEventListener("click",showSetup);id("restart").addEventListener("click",restart);id("next").addEventListener("click",newPuzzle);id("hint").addEventListener("click",hint);id("overlay-next").addEventListener("click",newPuzzle);id("overlay-list").addEventListener("click",goList);
 window.SudokuGame=Object.freeze({newPuzzle,restart,hint,enterValue,getState:()=>({...state,puzzle:copy(state.puzzle||[]),solution:copy(state.solution||[]),entries:copy(state.entries||[])}),packs});
 if(configurePlayer())document.querySelectorAll("[data-setting]").forEach(button=>button.setAttribute("aria-pressed",String(button.classList.contains("selected"))));
})();
