document.addEventListener('DOMContentLoaded',()=>{ if(window.SistersPlay) SistersPlay.showCoach('sudoku',[{demo:'1 2 3',line:'空格補上缺少的圖案'},{demo:'🚫',line:'同一排不能重複'}]); });
(() => {
 "use strict";
 const ui=window.SistersShared,content=window.SISTERS_CONTENT,engine=window.SudokuEngine;
 const packs={animals4:["🐱","🐶","🐰","🐻"],animals6:["🐱","🐶","🐰","🐻","🐼","🦊"]};
 const state={playerId:ui.loadPlayer(),size:4,mode:"number",difficulty:"practice",puzzle:null,solution:null,entries:null,selected:null,completed:false,lastSignature:"",hintsUsed:0,hintCell:null,conflicts:[]};
 const id=name=>document.getElementById(name),copy=board=>board.map(row=>[...row]);
 function goList(){location.href="../../index.html#games/logic";} function label(value){return state.mode==="picture"?packs[`animals${state.size}`][value-1]:String(value);}
 function configurePlayer(){if(!content.players[state.playerId]){goList();return false;}id("player-badge").replaceChildren(ui.makeReading(content.site.currentPlayer,{compact:true}),document.createTextNode("："),ui.makeReading(content.players[state.playerId].name,{compact:true}));return true;}
 function selectOption(button){const setting=button.dataset.setting,value=button.dataset.value;state[setting]=setting==="size"?Number(value):value;document.querySelectorAll(`[data-setting="${setting}"]`).forEach(item=>{const selected=item===button;item.classList.toggle("selected",selected);item.setAttribute("aria-pressed",String(selected));});}
 function signature(puzzle){return puzzle.flat().join("");} function hintLimit(){return state.size===4?3:2;} function boxOf(row,col){return `${Math.floor(row/2)},${Math.floor(col/(state.size===4?2:3))}`;}
 function newPuzzle(){let made;for(let i=0;i<8;i+=1){made=engine.generatePuzzle(state.size,state.difficulty);if(signature(made.puzzle)!==state.lastSignature)break;}state.puzzle=copy(made.puzzle);state.solution=copy(made.solution);state.entries=copy(made.puzzle);state.lastSignature=signature(made.puzzle);state.selected=null;state.completed=false;state.hintsUsed=0;state.hintCell=null;state.conflicts=[];id("complete").hidden=true;renderAll();}
 function showGame(){id("setup").hidden=true;id("game").hidden=false;newPuzzle();} function showSetup(){id("game").hidden=true;id("setup").hidden=false;}
 function candidates(row,col){if(state.entries[row][col])return [];const used=new Set(state.entries[row]);for(let r=0;r<state.size;r+=1)used.add(state.entries[r][col]);const [br,bc]=boxOf(row,col).split(",").map(Number),cols=state.size===4?2:3;for(let r=br*2;r<br*2+2;r+=1)for(let c=bc*cols;c<bc*cols+cols;c+=1)used.add(state.entries[r][c]);return Array.from({length:state.size},(_,i)=>i+1).filter(v=>!used.has(v));}
 function findConflicts(){const bad=new Set(),groups=[];for(let r=0;r<state.size;r+=1)groups.push(Array.from({length:state.size},(_,c)=>[r,c]));for(let c=0;c<state.size;c+=1)groups.push(Array.from({length:state.size},(_,r)=>[r,c]));const cols=state.size===4?2:3;for(let r=0;r<state.size;r+=2)for(let c=0;c<state.size;c+=cols){const group=[];for(let dr=0;dr<2;dr+=1)for(let dc=0;dc<cols;dc+=1)group.push([r+dr,c+dc]);groups.push(group);}groups.forEach(group=>{const seen=new Map();group.forEach(([r,c])=>{const value=state.entries[r][c];if(!value)return;if(seen.has(value)){bad.add(`${r},${c}`);bad.add(seen.get(value));}else seen.set(value,`${r},${c}`);});});return [...bad].map(key=>{const [row,col]=key.split(",").map(Number);return{row,col};});}
 function isRelated(row,col,target){return target&&(row===target.row||col===target.col||boxOf(row,col)===boxOf(target.row,target.col));}
 function cellClass(row,col,value){const classes=["sudoku-cell"];if(state.puzzle[row][col])classes.push("given");else classes.push("editable");if(state.selected&&state.selected.row===row&&state.selected.col===col)classes.push("selected");else if(isRelated(row,col,state.selected))classes.push("related");if(state.hintCell&&state.hintCell.row===row&&state.hintCell.col===col)classes.push("hint-target");else if(isRelated(row,col,state.hintCell))classes.push("hint-related");if(state.conflicts.some(item=>item.row===row&&item.col===col))classes.push("conflict");if(value)classes.push("filled");return classes.join(" ");}
 function renderBoard(){const board=id("board"),boxCols=state.size===4?2:3;board.style.setProperty("--size",state.size);board.replaceChildren();state.entries.forEach((line,row)=>line.forEach((value,col)=>{const button=document.createElement("button");button.type="button";button.className=cellClass(row,col,value);button.dataset.row=row;button.dataset.col=col;button.textContent=value?label(value):"";button.disabled=Boolean(state.puzzle[row][col])||state.completed;button.setAttribute("aria-label",value?`${row+1}列${col+1}行 ${label(value)}`:`${row+1}列${col+1}行 空格`);if((col+1)%boxCols===0&&col<state.size-1)button.classList.add("box-right");if((row+1)%2===0&&row<state.size-1)button.classList.add("box-bottom");button.addEventListener("click",()=>selectCell(row,col));board.append(button);}));}
 function renderAnswers(){const pad=id("answers");pad.style.setProperty("--size",state.size);pad.replaceChildren();for(let value=1;value<=state.size;value+=1){const button=document.createElement("button");button.type="button";button.className="answer-button";button.textContent=label(value);button.disabled=state.completed;button.addEventListener("click",()=>enterValue(value));pad.append(button);}}
 function renderHint(){const button=id("hint"),remaining=Math.max(0,hintLimit()-state.hintsUsed);id("hint-count").textContent=`${remaining} / ${hintLimit()}`;button.disabled=state.completed||remaining===0;}
 function renderAll(){renderBoard();renderAnswers();renderHint();id("game-meta").textContent=`${state.size}×${state.size}・${state.mode==="number"?"數字":"動物"}・${{practice:"練習 ⭐",easy:"簡單 ⭐⭐",challenge:"挑戰 ⭐⭐⭐"}[state.difficulty]}`;id("message").textContent="點一個空格，再選答案";}
 function selectCell(row,col){if(state.puzzle[row][col]||state.completed)return;state.selected={row,col};state.hintCell=null;renderBoard();id("message").textContent="選一個答案吧！";}
 function enterValue(value){if(!state.selected||state.completed){id("message").textContent="先點一個空格喔～";return;}const{row,col}=state.selected;state.entries[row][col]=value;state.conflicts=findConflicts();state.hintCell=null;renderBoard();if(state.conflicts.length){id("message").textContent="這附近好像有兩個一樣的數字，再看看？";return;}id("message").textContent=value===state.solution[row][col]?"答對了，繼續加油！":"再想想看～";if(isComplete())finish();}
 function isComplete(){return state.entries.every((row,r)=>row.every((value,c)=>value===state.solution[r][c]));} function finish(){if(state.completed)return;state.completed=true;renderBoard();renderAnswers();renderHint();id("complete").hidden=false;}
 function restart(){state.entries=copy(state.puzzle);state.selected=null;state.completed=false;state.hintCell=null;state.conflicts=[];id("complete").hidden=true;renderAll();}
 function hint(){if(state.completed||state.hintsUsed>=hintLimit())return;state.conflicts=findConflicts();if(state.conflicts.length){state.hintCell=null;renderBoard();id("message").textContent="這附近好像有兩個一樣的數字，再看看？";return;}const blanks=[];state.entries.forEach((line,row)=>line.forEach((value,col)=>{if(!value)blanks.push({row,col,options:candidates(row,col)});}));if(!blanks.length)return;const target=blanks.find(item=>item.options.length===1)||blanks.sort((a,b)=>a.options.length-b.options.length)[0];state.hintsUsed+=1;state.selected=target;state.hintCell=target;renderBoard();renderHint();id("message").textContent=target.options.length===1?"看看亮起來的這一格，它好像只剩一種可能喔！":"看看亮起來的這一格，再比對同一列、同一行和小方格喔！";}
 document.querySelectorAll("[data-setting]").forEach(button=>button.addEventListener("click",()=>selectOption(button)));id("start").addEventListener("click",showGame);id("back-list").addEventListener("click",goList);id("back-setup").addEventListener("click",showSetup);id("restart").addEventListener("click",restart);id("next").addEventListener("click",newPuzzle);id("hint").addEventListener("click",hint);id("overlay-next").addEventListener("click",newPuzzle);id("overlay-list").addEventListener("click",goList);
 window.SudokuGame=Object.freeze({newPuzzle,restart,hint,enterValue,findConflicts,candidates,getState:()=>({...state,puzzle:copy(state.puzzle||[]),solution:copy(state.solution||[]),entries:copy(state.entries||[])}),packs});if(configurePlayer())document.querySelectorAll("[data-setting]").forEach(button=>button.setAttribute("aria-pressed",String(button.classList.contains("selected"))));
})();
