'use strict';
// Reproducible original challenge banks. Geometry/logic, not icon relabelling,
// determines identity. Run from repository root; validators run separately.
const fs=require('fs');global.window={};require('../games/sudoku/engine.js');
let state=0x53525333;function random(){state^=state<<13;state^=state>>>17;state^=state<<5;return(state>>>0)/4294967296;}Math.random=random;
const pick=a=>a[Math.floor(random()*a.length)],shuffle=a=>{a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function normalize(a){const ids=new Map();return a.map(x=>!x?'0':(ids.has(x)?ids.get(x):(ids.set(x,ids.size+1),ids.get(x)))).join(',');}
function transforms(grid,all=true){const n=grid.length;let a=grid.map(r=>r.slice()),out=[];for(let k=0;k<(all?4:2);k++){out.push(a,a.map(r=>r.slice().reverse()));a=all?a[0].map((_,c)=>a.map(r=>r[c]).reverse()):a.slice().reverse();}return out;}
function emit(game,bank){for(const[k,a]of Object.entries(bank))if(a.length!==50)throw Error(game+k+a.length);fs.writeFileSync('assets/data/'+game+'-bank.js','/* Generated with tools/generate-basic.cjs; seed 0x53525333. */\nwindow.SistersBanks=window.SistersBanks||{};SistersBanks.'+game+'='+JSON.stringify(bank)+';\n');console.log(game,Object.keys(bank).length*50);}
let bank={};const E=window.SudokuEngine;
for(const n of[4,6])for(const d of['practice','easy','challenge']){const a=[],seen=new Set();let tries=0;while(a.length<50){if(++tries>100000)throw Error('Sudoku exhaustion');const q=E.generatePuzzle(n,d);if(q.puzzle.flat().filter(Boolean).length!==E.configs[n].clues[d])continue;const key=transforms(q.puzzle,n===4).map(g=>normalize(g.flat())).sort()[0];if(seen.has(key))continue;seen.add(key);a.push({...q,id:`${n}-${d}-${a.length}`,seed:state>>>0,clues:E.configs[n].clues[d]});}bank[n+':'+d]=a;}emit('sudoku',bank);
bank={};for(const count of[12,16,24,36]){const a=[],seen=new Set();while(a.length<50){const layout=shuffle(Array.from({length:count},(_,i)=>Math.floor(i/2)));const key=normalize(layout.map(x=>x+1));if(seen.has(key))continue;seen.add(key);a.push({id:`${count}-${a.length}`,layout});}bank[count]=a;}emit('memory',bank);
bank={};for(const k of[2,3,4,5,6]){const a=[],seen=new Set();while(a.length<50){const targets=shuffle(Array.from({length:36},(_,i)=>i)).slice(0,k).sort((a,b)=>a-b);const grid=Array.from({length:6},(_,r)=>Array.from({length:6},(_,c)=>+targets.includes(r*6+c)));const key=transforms(grid).map(g=>g.flat().join('')).sort()[0];if(seen.has(key))continue;seen.add(key);a.push({id:`${k}-${a.length}`,n:6,k,targets});}bank[k]=a;}emit('visual',bank);
function path(grid,start,goal){const Q=[start],prev=new Map([[start.join(),null]]);for(let i=0;i<Q.length;i++){const p=Q[i];if(goal&&p.join()===goal.join())break;for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const q=[p[0]+dr,p[1]+dc];if(grid[q[0]]?.[q[1]]===0&&!prev.has(q.join())){prev.set(q.join(),p);Q.push(q);}}}if(!goal)goal=Q.at(-1);const route=[];for(let p=goal;p;p=prev.get(p.join()))route.push(p);return{route:route.reverse(),seen:prev.size,goal};}
bank={};for(const[d,n]of Object.entries({easy:4,normal:5,hard:7,super:9})){const a=[],seen=new Set();while(a.length<50){const side=2*n+1,grid=Array.from({length:side},()=>Array(side).fill(1)),stack=[[0,0]],visited=new Set(['0,0']);grid[1][1]=0;while(stack.length){const[r,c]=stack.at(-1),opts=[[1,0],[-1,0],[0,1],[0,-1]].map(([dr,dc])=>[r+dr,c+dc,dr,dc]).filter(([nr,nc])=>nr>=0&&nc>=0&&nr<n&&nc<n&&!visited.has([nr,nc].join()));if(!opts.length){stack.pop();continue;}const[nr,nc,dr,dc]=pick(opts);visited.add([nr,nc].join());grid[r*2+1+dr][c*2+1+dc]=grid[nr*2+1][nc*2+1]=0;stack.push([nr,nc]);}
const start=[1,1],p=path(grid,start),marked=grid.map(r=>r.slice());marked[1][1]=2;marked[p.goal[0]][p.goal[1]]=3;const key=transforms(marked).map(g=>g.flat().join('')).sort()[0];if(seen.has(key))continue;seen.add(key);a.push({id:`${d}-${a.length}`,grid,start:{row:1,col:1},goal:{row:p.goal[0],col:p.goal[1]},pathLength:p.route.length-1,solution:p.route,logicalSize:n});}bank[d]=a;}emit('maze',bank);
function hNeighbors(v){const top=[null,null,null];v.forEach((p,i)=>{if(top[p]===null)top[p]=i;});const out=[];for(let from=0;from<3;from++)if(top[from]!==null)for(let to=0;to<3;to++)if(to!==from&&(top[to]===null||top[from]<top[to])){const q=v.slice();q[top[from]]=to;out.push({v:q,move:[from,to]});}return out;}
function hSolve(a,b){const q=[a],prev=new Map([[a.join(''),null]]),goal=b.join('');for(let i=0;i<q.length&&!prev.has(goal);i++)for(const next of hNeighbors(q[i])){const key=next.v.join('');if(!prev.has(key)){prev.set(key,{v:q[i],move:next.move});q.push(next.v);}}const moves=[];for(let k=goal;prev.get(k);){const p=prev.get(k);moves.push(p.move);k=p.v.join('');}return moves.reverse();}
const permutations=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];
bank={};for(const n of[3,4,5,6,7]){const a=[],seen=new Set();while(a.length<50){const start=Array.from({length:n},()=>Math.floor(random()*3)),goal=Array.from({length:n},()=>Math.floor(random()*3));const key=permutations.map(p=>start.map(x=>p[x]).join('')+':'+goal.map(x=>p[x]).join('')).sort()[0];if(seen.has(key))continue;const solution=hSolve(start,goal);if(solution.length<n||solution.length>2**n-1)continue;seen.add(key);a.push({id:`${n}-${a.length}`,n,start,goal,solution,minMoves:solution.length});}bank[n]=a;}emit('hanoi',bank);
bank={repeat:[],add:[],groups:[]};let seen=new Set();while(bank.repeat.length<50){const len=2+Math.floor(random()*6),raw=Array.from({length:len},()=>Math.floor(random()*4)),unit=normalize(raw.map(x=>x+1)).split(',').map(Number).map(x=>x-1);if(new Set(unit).size<2||Array.from({length:len-1},(_,i)=>i+1).some(k=>len%k===0&&unit.every((x,i)=>x===unit[i%k])))continue;const key=Array.from({length:len},(_,k)=>normalize(unit.slice(k).concat(unit.slice(0,k)).map(x=>x+1))).sort()[0];if(seen.has(key))continue;seen.add(key);const items=unit.concat(unit),symbols=['●','▲','■','★'];bank.repeat.push({id:'repeat-'+bank.repeat.length,kind:'repeat',unit:unit.map(x=>symbols[x]),items:items.map(x=>symbols[x]),answer:symbols[unit[0]],choices:shuffle([...new Set(symbols)]),rule:'這一組從頭重複：'+unit.map(x=>symbols[x]).join(' '),example:'例：● ▲｜● ▲｜下一個是 ●'});}
seen=new Set();while(bank.add.length<50){const start=Math.floor(random()*50),step=1+Math.floor(random()*9),key=start+':'+step;if(seen.has(key))continue;seen.add(key);const answer=start+4*step;bank.add.push({id:'add-'+bank.add.length,kind:'add',start,step,items:Array.from({length:4},(_,i)=>String(start+i*step)),answer:String(answer),choices:shuffle([answer,answer+1,answer-1].map(String)),rule:'每次加 '+step,example:'例：每次加 2，1 → 3 → 5 → 下一個是 7'});}
seen=new Set();while(bank.groups.length<50){const start=1+Math.floor(random()*4),repeat=2+Math.floor(random()*3),step=1+Math.floor(random()*3),length=repeat*(1+Math.floor(random()*3))+Math.floor(random()*repeat),key=[start,repeat,step,length].join();if(seen.has(key))continue;seen.add(key);const answer=start+Math.floor(length/repeat)*step;bank.groups.push({id:'groups-'+bank.groups.length,kind:'groups',start,repeat,step,length,items:Array.from({length:length},(_,i)=>String(start+Math.floor(i/repeat)*step)),answer:String(answer),choices:shuffle([answer,answer+1,answer-1].map(String)),rule:`同一數字連續 ${repeat} 次，再增加 ${step}`,example:'例：每個數字 2 次，再加 1：1 1｜2 2｜下一個是 3'});}emit('pattern',bank);
