(async()=>{
  'use strict';
  let n=3,pegs=[],moves=0,startedAt=0,restarts=0,selected=null,cancelDrag=null,suppressClick=false,target=[2,2,2],question=null;
  function pegsFrom(v){return[0,1,2].map(p=>v.map((at,i)=>at===p?i+1:null).filter(Boolean).reverse());}
  async function start(reason='new',nextN=n){return SistersRound.start(async()=>{n=nextN;if(reason==='restart')restarts++;if(reason!=='restart'||!question||question.n!==n)question=await SistersChallenges.draw('hanoi:'+n,SistersBanks.hanoi[n]);pegs=pegsFrom(question.start);target=question.goal.slice();moves=0;selected=null;startedAt=Date.now();document.getElementById('complete').hidden=true;chips();render();},reason);}
  function legal(from,to){const disc=pegs[from].at(-1),peg=pegs[to];return from!==to&&disc!==undefined&&(!peg.length||peg.at(-1)>disc);}
  function transfer(from,to){if(!SistersRound.canInteract())return;if(legal(from,to)){pegs[to].push(pegs[from].pop());moves++;selected=null;SistersPlay.playSound('ok');}else SistersPlay.playSound('soft');render();if(pegs.every((p,i)=>p.join()===pegsFrom(target)[i].join())){SistersPlay.showComplete(`排成目標了，用了 ${moves} 步`);SistersPlay.recordResult({difficulty:String(n),level:question?.id||n,startedAt,moves,restartCount:restarts});}SistersRound.checkpoint();}
  function choose(i){if(!SistersRound.canInteract()||suppressClick)return;if(selected===null){if(pegs[i].length)selected=i;render();SistersRound.checkpoint();}else{const from=selected;selected=null;transfer(from,i);}}
  function render(){const goal=document.getElementById('hanoi-goal');goal.replaceChildren();pegsFrom(target).forEach((peg,i)=>{const col=document.createElement('div');col.className='peg';col.setAttribute('aria-label',`目標第 ${i+1} 柱`);peg.forEach(d=>{const disc=document.createElement('div');disc.className='disc';disc.style.width=`${25+d/n*70}%`;disc.style.background=`hsl(${d*36},70%,72%)`;disc.textContent=d;col.append(disc);});goal.append(col);});const host=document.getElementById('pegs');host.replaceChildren();pegs.forEach((peg,i)=>{const col=document.createElement('div');col.className='peg'+(selected===i?' selected':'');col.dataset.i=i;col.tabIndex=0;col.setAttribute('role','button');col.setAttribute('aria-label',`第 ${i+1} 柱，${peg.length} 個圓盤`);col.onclick=()=>choose(i);col.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();choose(i);}};const tag=document.createElement('span');tag.className='peg-tag';tag.textContent=peg.length?'':'空柱';col.append(tag);peg.forEach((d,idx)=>{const el=document.createElement('div');el.className='disc';el.style.width=`${25+d/n*70}%`;el.style.background=`hsl(${d*36},70%,72%)`;if(idx===peg.length-1)el.onpointerdown=e=>drag(e,i,el);col.append(el);});host.append(col);});document.getElementById('status').textContent=`排成上方目標；大盤不能放在小盤上 · ${n} 層 · ${moves} 步 · 最少 ${question?.minMoves??2**n-1} 步`;}
  function drag(ev,from,el){if(!SistersRound.canInteract()||cancelDrag||ev.button!==0)return;ev.preventDefault();const rect=el.getBoundingClientRect(),offset={x:ev.clientX-rect.left,y:ev.clientY-rect.top};const ghost=el.cloneNode();Object.assign(ghost.style,{position:'fixed',zIndex:9,pointerEvents:'none',width:rect.width+'px',height:rect.height+'px',left:rect.left+'px',top:rect.top+'px'});document.body.append(ghost);el.style.opacity='.35';let moved=false;el.setPointerCapture(ev.pointerId);
    function cleanup(){el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',cancel);if(el.hasPointerCapture(ev.pointerId))el.releasePointerCapture(ev.pointerId);ghost.remove();el.style.opacity='';cancelDrag=null;document.querySelectorAll('.peg').forEach(c=>c.classList.remove('legal','illegal'));}
    function cancel(){cleanup();suppressClick=true;setTimeout(()=>suppressClick=false,300);}
    function move(e){if(e.pointerId!==ev.pointerId||!SistersRound.canInteract())return;if(Math.hypot(e.clientX-ev.clientX,e.clientY-ev.clientY)>5)moved=true;ghost.style.left=e.clientX-offset.x+'px';ghost.style.top=e.clientY-offset.y+'px';document.querySelectorAll('.peg').forEach(c=>{c.classList.toggle('legal',legal(from,+c.dataset.i));});}
    function up(e){if(e.pointerId!==ev.pointerId)return;cleanup();if(!moved){choose(from);suppressClick=true;setTimeout(()=>suppressClick=false,0);return;}const hit=[...document.querySelectorAll('.peg')].findIndex(c=>{const r=c.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;});suppressClick=true;setTimeout(()=>suppressClick=false,0);if(hit>=0)transfer(from,hit);else render();}
    cancelDrag=cancel;el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',cancel);
  }
  function chips(){SistersChallenges.selector(document.getElementById('disc-row'),[3,4,5,6,7].map(d=>({value:d,label:d+' 層'})),n,v=>start('new',+v),'圓盤數');}
  SistersPlay.showCoach('hanoi',[{demo:'🔴➡️',line:'拖圓盤，或選來源柱再選目的柱'}]);SistersPlay.mount({title:'河內塔',onRestart:()=>start('restart')});document.getElementById('overlay-next').onclick=()=>start();chips();if(!await SistersRound.attach({snapshot:()=>({n,pegs,moves,startedAt,restarts,selected,target,question}),cancel:()=>cancelDrag?.(),restore:p=>{({n,pegs,moves,startedAt,restarts,selected}=p);target=p.target||Array(n).fill(2);question=p.question||null;chips();render();}}))await start();
})();
